create table if not exists public.votes (
  id bigint generated by default as identity primary key,
  title text not null default '',
  created_at timestamptz not null default now(),
  active boolean not null default true
);

create table if not exists public.vote_options (
  id bigint generated by default as identity primary key,
  vote_id bigint not null references public.votes(id) on delete cascade,
  name text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.vote_responses (
  id bigint generated by default as identity primary key,
  vote_id bigint not null references public.votes(id) on delete cascade,
  option_id bigint not null references public.vote_options(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (vote_id, user_id)
);

alter table public.vote_responses enable row level security;
alter table public.vote_options enable row level security;
alter table public.votes enable row level security;

create policy "Anyone can read votes"
  on public.votes for select using (true);
create policy "Anyone can read vote_options"
  on public.vote_options for select using (true);
create policy "Anyone can read vote_responses"
  on public.vote_responses for select using (true);

create policy "Authenticated users can insert vote_responses"
  on public.vote_responses for insert
  with check (auth.role() = 'authenticated');
