create table if not exists public.restaurants (
  id bigint generated by default as identity primary key,
  name text not null,
  description text not null default '',
  address text not null default '',
  category text not null default '',
  lat double precision,
  lng double precision,
  added_by uuid references auth.users(id),
  created_at timestamptz not null default now()
);

alter table public.restaurants enable row level security;

create policy "Anyone can read restaurants"
  on public.restaurants for select using (true);

create policy "Authenticated users can insert restaurants"
  on public.restaurants for insert
  with check (auth.role() = 'authenticated');
